### ISSUE TITLE
As a player I want to be able to use a voice chat to communicate with my teammate

### ISSUE THREAD

**Issue by ambros02** [Sopra-FS24-group-30/sopra-fs24-group-30-server#12]
- [ ] Sopra-FS24-group-30/sopra-fs24-group-30-server#70
- [ ] Sopra-FS24-group-30/sopra-fs24-group-30-client#108
- [ ] Sopra-FS24-group-30/sopra-fs24-group-30-client#105
- [ ] Sopra-FS24-group-30/sopra-fs24-group-30-client#109
- [ ] Sopra-FS24-group-30/sopra-fs24-group-30-client#97

Optional:
- [ ] Players can switch between the global and team voice chat

Acceptance criteria:
- [ ] the voice chat consumes an external API
- [ ] the voice chat allows for clear and easy communication
