### ISSUE TITLE
As a player I want to be able to use items before rolling a dice

### ISSUE THREAD

**Issue by ambros02** [Sopra-FS24-group-30/sopra-fs24-group-30-server#14]
- [x] Sopra-FS24-group-30/sopra-fs24-group-30-server#84
- [x] Sopra-FS24-group-30/sopra-fs24-group-30-server#81
- [x] Sopra-FS24-group-30/sopra-fs24-group-30-server#82

Acceptance criteria:
- [x] the item can only be used before throwing the dice
- [x] the item and ultimate can be used interchangeably
